{
    "name": "OduMCP",
    "summary": "Secure policy, approval, and audit layer for external MCP servers",
    "description": "Connect external MCP clients to Odoo through explicit policies, approvals, and audit logging.",
    "version": "17.0.1.1.0",
    "category": "Technical",
    "website": "https://github.com/oduist/connect_addons_ng",
    "author": "Connect MCP Contributors",
    "license": "LGPL-3",
    "depends": ["auth_totp", "base", "bus", "mail", "web", "web_editor"],
    "data": [
        "security/mcp_security.xml",
        "security/ir.model.access.csv",
        "data/odumcp_data.xml",
        "views/profile_views.xml",
        "views/res_users_views.xml",
        "views/res_users_apikeys_views.xml",
        "views/approval_views.xml",
        "views/audit_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "odumcp/static/src/scss/yaml_preview.scss",
        ],
    },
    "application": False,
    "installable": True,
}
