{'name': 'OduPilot',
 'version': '18.0.1.0.0',
 'author': 'Odooist',
 'maintainer': 'Odooist',
 'license': 'OPL-1',
 'category': 'Productivity/Discuss',
 'summary': 'OpenCode AI sessions in Odoo Discuss',
 'depends': ['mail', 'auth_totp', 'odumcp'],
 'external_dependencies': {'python': ['markdown-it-py', 'linkify-it-py', 'requests']},
 'data': ['security/odupilot_groups.xml',
          'security/odupilot_security.xml',
          'security/ir.model.access.csv',
          'data/odupilot_data.xml',
          'views/odupilot_runtime_views.xml',
          'views/odupilot_mcp_server_views.xml',
          'views/odupilot_agent_views.xml',
          'views/odupilot_agent_log_views.xml',
          'views/odupilot_profile_views.xml',
          'views/odupilot_session_views.xml',
          'wizards/odupilot_ask_wizard_views.xml',
          'wizards/odupilot_developer_wizard_views.xml',
          'views/res_users_views.xml',
          'views/res_config_settings_views.xml',
          'views/odupilot_menu.xml'],
 'assets': {'web.assets_backend': ['odupilot/static/src/js/chatter_ask_ai.js',
                                   'odupilot/static/src/js/developer_debug_item.js',
                                   'odupilot/static/src/js/voice_recorder.js',
                                   'odupilot/static/src/js/voice_text_field.js',
                                   'odupilot/static/src/js/discuss_ai_category.js',
                                   'odupilot/static/src/js/stream_state.js',
                                   'odupilot/static/src/js/permission_message.js',
                                   'odupilot/static/src/scss/permission_message.scss',
                                   'odupilot/static/src/scss/chatter_answer.scss',
                                   'odupilot/static/src/scss/voice_text_field.scss',
                                   'odupilot/static/src/xml/chatter_ask_ai.xml',
                                   'odupilot/static/src/xml/permission_message.xml',
                                   'odupilot/static/src/xml/voice_text_field.xml'],
            'web.assets_unit_tests': ['odupilot/static/tests/stream_state.test.js']},
 'installable': True,
 'application': False,
 'post_init_hook': 'post_init_hook'}
